name: น้องโปรแกรม
title: เรียนโปรแกรมง่ายๆกับน้องโปรแกรม
description: เรียนโปรแกรมกับเราฟรีผ่าน GitHub.com สำหรับผู้ที่ต้องการเริ่มแบบง่ายๆ รวดเร็ว และมีการสอนใช้เครื่องมือที่ทันสมัยกว่า
repository: https://github.com/nakorndev/nong-program
url: https://nakorndev.github.io
baseurl: /nong-program

author: nakorndev
email: nakorndev@gmail.com
twitter:
  username: nakorndev
facebook:
  publisher: 1944714005562794
logo: /assets/icons/source.png
social:
  name: พี่บอล สอนโปรแกรมแบบโง่ๆ
  links:
    - https://twitter.com/nakorndev
    - https://www.facebook.com/1944714005562794
    - https://github.com/nakorndev
    - https://www.patreon.com/bePatron?c=1655061
google_site_verification: oBl61nKg-qYqrRiLnf60ML1QdnXyyLx1WiyRQaA9gOA

version:
  bulma: 0.7.0
  fontawesome: 5.0.10
  tippyjs: 2.5.2
  noty: 3.1.4

navigation:
  github: nakorndev/nong-program
  facebook: 1944714005562794
  patreon: bePatron?c=1655061

timezone: Asia/Bangkok
lang: th_TH
markdown: kramdown
excerpt_separator: <!--more-->
date_format: '%B %d, %Y'

sass:
  style: compressed

plugins:
  - github-pages
  - jekyll-feed
  - jekyll-compose
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-admin

collections:
  docs:
    permalink: /docs/:path/
    output: true
  news:
    permalink: /news/:year/:month/:day/:title
    output: true
  examples:
    permalink: /examples/:path/
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      is_post: true
  - scope:
      path: _docs
      type: docs
    values:
      layout: doc
      is_doc: true
  - scope:
      path: _examples
      type: examples
    values:
      layout: example
      is_example: true

exclude: [
  assets/images/_achieve/*,
  _docs/_achieve/*,
  vendor,
  script,
  Gemfile,
  Gemfile.lock
]
