name: "nong-program"
title: "บล็อกดีๆเพื่อแฟนๆของน้องโปรแกรม"
description: "เว็บบล็อกโดยแฟนๆของน้องโปรแกรม สำหรับผู้ที่หลงรักการเขียนโปรแกรม หรืออยากจะลองคบหาดูใจกับการเขียนโปรแกรมสักระยะ สามารถมีส่วนร่วมในการพัฒนาบทความเพื่อการเรียนรู้ไปกับเราได้"
repository: "https://github.com/nakorndev/nong-program"
timezone: "Asia/Bangkok"
lang: "th"
email: "nakorndev@gmail.com"
baseurl: "/nong-program"
url: "https://nakorndev.github.io"

markdown: kramdown
theme: jekyll-bulma-theme
plugins:
  - jekyll-feed
  - jekyll-paginate

version:
  bulma: 0.6.2
  font-awesome: 5.0.8

navigation:
  github: nakorndev/nong-program
  facebook: 777742965747869

paginate: 5
excerpt_separator: <!--more-->
date_format: '%B %d, %Y'

sass:
  style: compressed

collections:
  docs:
    permalink: "/docs/:path/"
    output: true
  news:
    permalink: "/news/:year/:month/:day/:title"
    output: true
  awesome:
    permalink: "/awesome/:path/"
    output: true

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
      is_post: true
      title: nong-program Posts
      subtitle: โพสต์ของน้องโปรแกรม
  - scope:
      path: _docs
      type: docs
    values:
      layout: doc
      is_doc: true
      title: Documentation
      subtitle: เอกสารสำหรับผู้เริ่มต้นเป็นแฟนๆน้องโปรแกรม
  - scope:
      path: _news
      type: news
    values:
      layout: news
      is_news: true
      title: News
      subtitle: ข่าวสารที่เกี่ยวข้องกับน้องโปรแกรม
  - scope:
      path: _awesome
      type: awesome
    values:
      layout: awesome
      is_awesome: true
      title: Awesome
      subtitle: รวมข้อมูลดีๆที่ต้องน้องยังร้อง "AWESOME!"
