production: true
name: น้องโปรแกรม
title: เรียนโปรแกรมง่ายๆกับน้องโปรแกรม
description: เรียนโปรแกรมกับเราฟรีผ่าน GitHub สำหรับผู้ที่ต้องการเริ่มแบบอย่างง่าย รวดเร็ว สามารถร่วมดัดแปลงเนื้อหาบนเว็บไซต์เราพร้อมกันได้ พร้อมกับการฝึกใช้งาน GitHub เพื่อให้สามารถเริ่มเขียน Source code ในการฝึกฝนตนเองผ่านชุมชนการพัฒนาโปรแกรมที่มีผู้ใช้งานมากที่สุด
repository: https://github.com/nakorndev/nong-program
url: https://nakorndev.github.io
baseurl: /nong-program

author: nakorndev
email: nakorndev@gmail.com
twitter:
  username: nakorndev
facebook:
  app_id: 384680698713517
  publisher: 173978953317093
logo: /assets/icons/source.png
social:
  name: โลกกลมๆของนายบอล
  links:
    - https://twitter.com/nakorndev
    - https://www.facebook.com/173978953317093
    - https://github.com/nakorndev
    - https://www.patreon.com/bePatron?c=1655061
google_site_verification: oBl61nKg-qYqrRiLnf60ML1QdnXyyLx1WiyRQaA9gOA
seo:
  name: เรียนโปรแกรมง่ายๆกับน้องโปรแกรม
  type: article

version:
  bulma: 0.7.1
  fontawesome: 5.0.12
  tippyjs: 2.5.2
  noty: 3.1.4
  vue: 2.5.16
  moment: 2.22.1

navigation:
  github: nakorndev/nong-program
  facebook: 173978953317093
  patreon: bePatron?c=1655061

timezone: Asia/Bangkok
lang: th_TH
markdown: kramdown
excerpt_separator: <!--more-->
date_format: '%B %d, %Y'

sass:
  style: compressed

plugins:
  - github-pages
  - jekyll-feed
  - jekyll-compose
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-admin

collections:
  docs:
    permalink: /docs/:path/
    output: true
  examples:
    permalink: /examples/:path/
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/og.jpg
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      is_post: true
  - scope:
      path: _docs
      type: docs
    values:
      layout: doc
      is_doc: true
  - scope:
      path: _examples
      type: examples
    values:
      layout: example
      is_example: true

exclude: [
  assets/images/_achieve/*,
  _docs/_achieve/*,
  vendor,
  script,
  Gemfile,
  Gemfile.lock
]
