name: น้องโปรแกรม
title: เรียนโปรแกรมง่ายๆกับน้องโปรแกรม
description: เรียนโปรแกรมกับเราฟรีผ่าน GitHub.com สำหรับผู้ที่ต้องการเริ่มแบบง่ายๆ รวดเร็ว และมีการสอนใช้เครื่องมือที่ทันสมัยกว่า
repository: https://github.com/nakorndev/nong-program
timezone: Asia/Bangkok
lang: th
email: nakorndev@gmail.com
baseurl: /nong-program
url: https://nakorndev.github.io

exclude: [
  assets/images/_achieve/*,
  _docs/_achieve/*,
  vendor
]

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

version:
  bulma: 0.7.0
  fontawesome: 5.0.10
  tippyjs: 2.5.2
  noty: 3.1.4

navigation:
  github: nakorndev/nong-program
  facebook: 777742965747869
  patreon: bePatron?c=1655061

paginate: 5
excerpt_separator: <!--more-->
date_format: '%B %d, %Y'

sass:
  style: compressed

collections:
  docs:
    permalink: /docs/:path/
    output: true
  news:
    permalink: /news/:year/:month/:day/:title
    output: true
  awesome:
    permalink: /awesome/:path/
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      is_post: true
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
      is_docs: true
  - scope:
      path: _news
      type: news
    values:
      layout: news
      is_news: true
  - scope:
      path: _awesome
      type: awesome
    values:
      layout: awesome
      is_extra: true
